version: '3.7'

services:
  db-test:
    image: mysql:8
    container_name: db-test
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
        - "3306:3306"
    volumes:
      - ./sql/init_test.sql:/docker-entrypoint-initdb.d/init_test.sql
